import { Transaction, LeaderboardEntry, SmartBin, RewardItem } from './types';

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    type: 'deposit',
    title: 'Smart Can #402 • Broadway Plaza',
    location: 'Broadway Plaza & 34th St, NYC',
    details: '3x PET Plastic bottles • 0.18 kg verified via Optical Sensor',
    amount: 45,
    timestamp: '22m ago',
    category: 'plastic',
    txHash: '0x8f2a9e14c33d7b8890ab21e3f60718a221f479bb3c',
    sensorId: 'OPT-402-NY',
    weightKg: 0.18,
  },
  {
    id: 'tx-002',
    type: 'deposit',
    title: 'Smart Can #118 • Central Park North',
    location: 'Central Park N & 110th St, NYC',
    details: '1x Aluminum Can • Weight 0.04 kg certified',
    amount: 20,
    timestamp: 'Yesterday',
    category: 'aluminum',
    txHash: '0x33e8b091fca718227b409e6c2a510de381b892aa19',
    sensorId: 'LOAD-118-NY',
    weightKg: 0.04,
  },
  {
    id: 'tx-003',
    type: 'deposit',
    title: 'E-Waste Depot • Downtown Node',
    location: 'Fulton St Terminal, Manhattan',
    hazardLevel: 'High Hazard',
    details: '1x Lithium Polymer Battery • Heavy Metals Secured',
    amount: 150,
    timestamp: '3 days ago',
    category: 'ewaste',
    txHash: '0x712a819bb01e4fc290a6e380f2d991ca438b001ef7',
    sensorId: 'SPEC-NODE-DWTN',
    weightKg: 0.22,
  },
  {
    id: 'tx-004',
    type: 'redemption',
    title: 'Redeemed $10 Whole Foods Voucher',
    location: 'EcoDrop Rewards Marketplace',
    details: 'Marketplace Order #WF-9942 • Digital Barcode Active',
    amount: -1000,
    timestamp: '5 days ago',
    category: 'reward',
    txHash: '0x992b4fa12001bbcf7728da491209ccbbffaa301290',
  },
];

export const INITIAL_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, initials: 'JD', name: 'Julian D.', amount: 3890, badge: 'gold' },
  { rank: 2, initials: 'SL', name: 'Sarah Lin', amount: 3410, badge: 'Top 1%' },
  { rank: 3, initials: 'TK', name: 'Tyler K.', amount: 2950, badge: 'Top 2%' },
  { rank: 14, initials: 'A', name: 'Altan (You)', amount: 1420, badge: '+80 to #13', isUser: true },
];

export const EXTENDED_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, initials: 'JD', name: 'Julian D.', amount: 3890, badge: 'gold' },
  { rank: 2, initials: 'SL', name: 'Sarah Lin', amount: 3410, badge: 'Top 1%' },
  { rank: 3, initials: 'TK', name: 'Tyler K.', amount: 2950, badge: 'Top 2%' },
  { rank: 4, initials: 'EW', name: 'Elena Watson', amount: 2780, badge: 'Top 2%' },
  { rank: 5, initials: 'MR', name: 'Marcus Rivera', amount: 2610, badge: 'Top 3%' },
  { rank: 6, initials: 'AK', name: 'Anya Kapoor', amount: 2490, badge: 'Top 3%' },
  { rank: 7, initials: 'DL', name: 'David Lee', amount: 2280, badge: 'Top 4%' },
  { rank: 8, initials: 'SM', name: 'Sofia Mendes', amount: 2150, badge: 'Top 4%' },
  { rank: 9, initials: 'CB', name: 'Chloe Bennett', amount: 1990, badge: 'Top 4%' },
  { rank: 10, initials: 'JP', name: 'Jordan Patel', amount: 1840, badge: 'Top 4%' },
  { rank: 11, initials: 'NH', name: 'Noah Hayes', amount: 1720, badge: 'Top 4%' },
  { rank: 12, initials: 'OG', name: 'Olivia Garcia', amount: 1590, badge: 'Top 4%' },
  { rank: 13, initials: 'LZ', name: 'Liam Zhang', amount: 1500, badge: '+80 ahead' },
  { rank: 14, initials: 'A', name: 'Altan (You)', amount: 1420, badge: '+80 to #13', isUser: true },
  { rank: 15, initials: 'MC', name: 'Mia Chen', amount: 1380, badge: '-40 behind' },
  { rank: 16, initials: 'RH', name: 'Rafael Silva', amount: 1290, badge: 'Top 5%' },
];

export const SMART_BINS_DATA: SmartBin[] = [
  {
    id: 'bin-402',
    name: 'Smart Can #402',
    location: 'Broadway Plaza & 34th St, Herald Square',
    distance: '0.2 mi away',
    status: 'online',
    capacityPct: 42,
    acceptedTypes: ['PET Plastic', 'Aluminum', 'Glass'],
  },
  {
    id: 'bin-118',
    name: 'Smart Can #118',
    location: 'Central Park North & 110th St Entrance',
    distance: '0.8 mi away',
    status: 'online',
    capacityPct: 68,
    acceptedTypes: ['PET Plastic', 'Aluminum'],
  },
  {
    id: 'bin-node-dwtn',
    name: 'E-Waste Depot • Downtown Node',
    location: 'Fulton Transit Center, Concourse B',
    distance: '1.4 mi away',
    status: 'online',
    capacityPct: 25,
    acceptedTypes: ['E-Waste', 'PET Plastic', 'Aluminum', 'Glass'],
    bonusMultiplier: 1.5,
  },
  {
    id: 'bin-512',
    name: 'Smart Can #512',
    location: 'Williamsburg Ferry Terminal Pier',
    distance: '1.7 mi away',
    status: 'high_capacity',
    capacityPct: 88,
    acceptedTypes: ['PET Plastic', 'Aluminum', 'Glass'],
  },
  {
    id: 'bin-204',
    name: 'Smart Can #204',
    location: 'DUMBO Archway & Water Street',
    distance: '2.1 mi away',
    status: 'online',
    capacityPct: 31,
    acceptedTypes: ['PET Plastic', 'Aluminum'],
  },
];

export const REWARDS_CATALOG: RewardItem[] = [
  {
    id: 'rew-1',
    title: '$10 Whole Foods Voucher',
    category: 'Groceries & Organic',
    costEco: 1000,
    usdValue: '$10.00 USD',
    sponsor: 'Whole Foods Market',
    stock: 24,
    description: 'Redeemable nationwide for fresh, organic groceries and zero-waste bulk goods.',
    icon: 'shopping_bag',
  },
  {
    id: 'rew-2',
    title: '$15 Patagonia Worn Wear Voucher',
    category: 'Sustainable Apparel',
    costEco: 1500,
    usdValue: '$15.00 USD',
    sponsor: 'Patagonia',
    stock: 12,
    description: 'Valid for gear repairs, recycled textile apparel, or sustainable outdoor equipment.',
    icon: 'checkroom',
  },
  {
    id: 'rew-3',
    title: '1-Week MTA MetroPass Unlimited',
    category: 'Clean Transit',
    costEco: 3300,
    usdValue: '$33.00 USD',
    sponsor: 'MTA Green Transit Initiative',
    stock: 50,
    description: 'Unlimited 7-day rides across NYC Subway and OMNY electric bus network.',
    icon: 'directions_subway',
  },
  {
    id: 'rew-4',
    title: 'Plant 2 Urban Native Saplings',
    category: 'Impact Donation',
    costEco: 500,
    usdValue: '$5.00 USD',
    sponsor: 'MillionTrees NYC',
    stock: 999,
    description: 'Directly fund the planting and 5-year maintenance of native oaks in Brooklyn parks.',
    icon: 'park',
  },
  {
    id: 'rew-5',
    title: '$25 REI Co-op Gift Card',
    category: 'Outdoor & Gear',
    costEco: 2500,
    usdValue: '$25.00 USD',
    sponsor: 'REI Co-op',
    stock: 18,
    description: 'Support your sustainable adventures with eco-certified outdoor hiking gear.',
    icon: 'hiking',
  },
  {
    id: 'rew-6',
    title: 'Fair-Trade Organic Coffee 12oz Bag',
    category: 'Food & Beverage',
    costEco: 800,
    usdValue: '$8.00 USD',
    sponsor: 'Devocion Roasters NYC',
    stock: 35,
    description: 'Freshly roasted single-origin shade-grown beans in 100% compostable packaging.',
    icon: 'coffee',
  },
];
